### ISSUE TITLE
Documentation for version 4.0.0 not pointing to correct github link

### ISSUE THREAD

**Issue by D4no0** [J0/phoenix_gen_socket_client#61]
Documentation is pointing to tag "v4.0.0" while the tag used on github is "4.0.0".

**Comment by J0** [comment]
Thanks for catching this  @D4no0 !
We will ammend this accordingly.

**Comment by J0** [comment]
So as it turns out, I need to publish a tag on the relevant Github commit as well. Sorry about that and thank you for your patience.

Should work fine now -- please feel free to reach out if you encounter any further issues/queries :)

Have a great day ahead!
